config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :page_configurations, only: [:index, :edit, :update]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :teams, only: [:index, :new, :create, :edit, :update, :destroy] do
    put :confirm, on: :member
    collection do
      get :recruit
      post :recruit_user
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    delete :delete_team, on: :member
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root to: 'main#home'

  get 'panel_one'   => 'main#panel_one'
  get 'panel_two'   => 'main#panel_two'
  get 'panel_three' => 'main#panel_three'
  get 'panel_four'  => 'main#panel_four'
  get 'panel_five'  => 'main#panel_five'
  get 'panel_six'   => 'main#panel_six'

  namespace :api do
    get 'get_teams' => 'api#get_teams'
    get 'get_teams_and_users' => 'api#get_teams_and_users'
    post 'nuevo_juego' => 'api#new_play'
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :edit, :update]
  layout 'application_sign_up'

  def new; end

  def create
    @user = User.find_by_email(params[:email])

    @user.deliver_reset_password_instructions! if @user

    redirect_to login_path, notice: 'Se enviaron las instrucciones para recuperar la clave a tu email.'
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password!(params[:user][:password])
      redirect_to login_path, notice: 'La clave se cambió exitosamente'
    else
      render :edit
    end
  end
end

app/views/password_resets/_form.html.erb
<%= form_tag password_resets_path, :method => :post, class: 'm-t' do %>
  <div class="form-group">
    <%= email_field_tag :email, nil, class: 'form-control', placeholder: 'Email', required: true %>
  </div>

  <%= submit_tag 'Enviar nueva clave',
    class: 'btn btn-primary block full-width m-b',
    data: { 'disable-with' => 'Enviando...' } %>

<% end %>

app/views/password_resets/_reset_password_form.html.erb
<%= form_with(model: user, local: true, url: password_reset_path(@token), method: :put, class: 'm-t') do |f| %>

  <div class="form-group">
    <%= f.email_field :email, placeholder: 'Email', class: 'form-control', disabled: true %>
  </div>

  <fieldset class="form-group">
   <%= f.password_field :password, placeholder: 'Clave', id: :user_password,
       class: 'form-control', required: true %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.password_field :password_confirmation, placeholder: 'Confirmación de clave', id: :user_password_confirmation,
        class: 'form-control', required: true %>
  </fieldset>

  <%= submit_tag 'Cambiar clave',
    class: 'btn btn-primary block full-width m-b',
    data: { 'disable-with' => 'Cambiando clave...' } %>

  <p class="text-muted text-center"><small>Ya sos parte de un equipo?</small></p>

  <%= link_to 'Login', login_path, class: 'btn btn-sm btn-white btn-block' %>
<% end %>

app/views/password_resets/edit.html.erb
<% provide(:title_header, 'Cambiar mi clave') %>
<% provide(:action_name, 'Recupero de clave') %>

<div class="row">
  <div class="col-md-12">
    <div class="ibox-content">

      <h2 class="font-bold">Cambiar mi clave</h2>

      <div class="row">

        <div class="col-lg-12">
          <%= render 'reset_password_form', user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title_header, 'Olvidé mi clave') %>
<% provide(:action_name, 'Recuperación de clave') %>

<div class="row">
  <div class="col-md-12">
    <div class="ibox-content">

      <h2 class="font-bold">Olvidé mi clave</h2>

        <p>
          Ingresa tu dirección de email y te enviaremos las instrucciones para recuperar tu clave.
        </p>

      <div class="row">

        <div class="col-lg-12">
          <%= render 'form'%>
        </div>
      </div>
    </div>
  </div>
</div>