config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :page_configurations, only: [:index, :edit, :update]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :teams, only: [:index, :new, :create, :edit, :update, :destroy] do
    put :confirm, on: :member
    collection do
      get :recruit
      post :recruit_user
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    delete :delete_team, on: :member
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root to: 'main#home'

  get 'panel_one'   => 'main#panel_one'
  get 'panel_two'   => 'main#panel_two'
  get 'panel_three' => 'main#panel_three'
  get 'panel_four'  => 'main#panel_four'
  get 'panel_five'  => 'main#panel_five'
  get 'panel_six'   => 'main#panel_six'

  namespace :api do
    get 'get_teams' => 'api#get_teams'
    get 'get_teams_and_users' => 'api#get_teams_and_users'
    post 'nuevo_juego' => 'api#new_play'
  end
end

app/models/page_configuration.rb
class PageConfiguration < ApplicationRecord

  # -- Validations
  validates :name, presence: true
  validates :value, presence: true
end

app/controllers/page_configurations_controller.rb
class PageConfigurationsController < ApplicationController
  before_action :set_page_configuration, only: [:edit, :update]

  def index
    @configurations = PageConfiguration.all
  end

  def edit; end

  def update
    if @page_configuration.update(page_configuration_params)
      redirect_to page_configurations_path, notice: 'La configuración se modificó exitosamente.'
    else
      flash[:error] = 'Ocurrió un error al modificar la configuración. Por favor intente nuevamente'
      render :edit
    end
  end

  private

  def set_page_configuration
    @page_configuration = PageConfiguration.find(params[:id])
  end

  def page_configuration_params
    params.require(:page_configuration).permit(:name, :value)
  end
end

app/views/page_configurations/_form.html.erb
<%= form_with(model: page_configuration, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'Nombre', class: 'form-control', disabled: true %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :value, placeholder: 'Valor', class: 'form-control', required: true %>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group actions">
        <%= f.submit 'Guardar configuración', class: "btn btn-success", data:
          { 'disable-with' => 'Guardando...' } %>
          <%= link_to 'Volver', :back, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/page_configurations/_page_configuration.html.erb
<tr>
  <td><%= page_configuration.name %></td>
  <td><%= page_configuration.value %></td>
  <td>
    <%= link_to 'Editar', edit_page_configuration_path(page_configuration), class: 'btn btn-xs btn-primary' %>
  </td>
</tr>

app/views/page_configurations/edit.html.erb
<% provide(:title_header, 'Editar configuración')%>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Editar configuración</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li>
        <%= link_to users_path do %>
          <%= fa_icon 'cog', text: 'Configuración' %>
          <% end %>
      </li>
      <li class="active">Editar configuración</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body">
      <%= render 'form', page_configuration: @page_configuration %>
    </div>
  </div>
</section>

app/views/page_configurations/index.html.erb
<% provide(:title_header, 'Configuración') %>

<header class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Configuración</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>
          <%= fa_icon 'home', text: 'Inicio' %>
          <% end %>
      </li>
      <li class="active">Configuración</li>
    </ol>
  </div>
</header>

<section class="wrapper wrapper-content animated fadeInRight">
  <div class="panel">
    <div class="panel-body responsive-table">

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Valor</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @configurations %>
        </tbody>
      </table>

      <% if @configurations.empty? %>
        <p class="lead text-center"> Nada que mostrar por aquí </p>
      <% end %>

    </div>
  </div>
</section>