config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :page_configurations, only: [:index, :edit, :update]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :teams, only: [:index, :new, :create, :edit, :update, :destroy] do
    put :confirm, on: :member
    collection do
      get :recruit
      post :recruit_user
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy] do
    delete :delete_team, on: :member
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root to: 'main#home'

  get 'panel_one'   => 'main#panel_one'
  get 'panel_two'   => 'main#panel_two'
  get 'panel_three' => 'main#panel_three'
  get 'panel_four'  => 'main#panel_four'
  get 'panel_five'  => 'main#panel_five'
  get 'panel_six'   => 'main#panel_six'

  namespace :api do
    get 'get_teams' => 'api#get_teams'
    get 'get_teams_and_users' => 'api#get_teams_and_users'
    post 'nuevo_juego' => 'api#new_play'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  layout 'application_sign_up'

  def new; end

  def create
    @user = login(params[:username], params[:password])
    if @user && (@user.admin? || (@user.team.present? && @user.team.is_approved?))
      redirect_to home_path, notice: 'Se ha logueado exitosamente'
    else
      flash[:error] = 'Ocurrió un error al intentar iniciar sesión. Por favor intentar nuevamente'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'Su sesión se cerró exitosamente.')
  end
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, method: :post do %>
  <fieldset class="form-group">
    <%= text_field_tag :username, nil, autofocus: true, autocomplete: :off,
          placeholder: 'Usuario', class: 'form-control', required: true %>
  </fieldset>

  <fieldset class="form-group">
    <%= password_field_tag :password, nil, placeholder: 'Contraseña',
      class: 'form-control', required: true %>
  </fieldset>

  <%= submit_tag 'Iniciar sesión',
    class: 'btn btn-primary block full-width m-b',
    data: { 'disable-with' => 'Iniciando...' } %>

  <%= link_to new_password_reset_path do %>
    <small>Olvidó la clave?</small>
  <% end %>
  <p class="text-muted text-center"><small>No tenes equipo?</small></p>
  <%= link_to 'Crear un equipo', new_team_path, class: 'btn btn-sm btn-white btn-block' %>
  <%= link_to 'Unite a un equipo', recruit_teams_path, class: 'btn btn-sm btn-white btn-block' %>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<% provide(:title_header, 'Inicio de sesión') %>
<% provide(:action_name, 'Inicia sesión') %>
<section>
  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>
</section>